name: scheduled_run

on:
  schedule: 
    - cron: 30 15 * * 1,3,5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: PullCodeFromRemoteRep
        uses: actions/checkout@v4

      - name: Install Node.JS
        uses: actions/setup-node@v4

      - name: Install Newman and HTML Extra reporter
        run: | 
         npm install -g newman
         npm install -g newman-reporter-htmlextra

      - name: Run POSTMAN collection
        run: | 
          newman run "collection\TRELLO_Sergey_test.postman_collection.json" --environment "collection\Trello_environment.postman_environment.json"
          -r htmlextra --reporter-htmlextra-export report\report.html

      - name: CLI reporter
        uses: stoe/action-reporting-cli  
        with:
          name: CLI report
          pth: report
