name: scheduled_run

on:
  workflow_dispatch:
  schedule: 
    - cron: 30 15 * * 1,3,5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: PullCodeFromRemoteRep
        uses: actions/checkout@v4

      - name: Install Node.JS
        uses: actions/setup-node@v4

      - name: Install Newman and HTML Extra reporter
        run: | 
         npm install -g newman
         npm install -g newman-reporter-htmlextra
      
      - name: Run POSTMAN collection
        run: | 
          newman run TRELLO_Sergey_test.postman_collection.json --environment Trello_environment.postman_environment.json -r htmlextra --reporter-htmlextra-export Extra_report.html || true
        
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: Extra_report.html  

      - name: Send report mail
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            # Server port, default 25:
            server_port: 465
            # Optional whether this connection use TLS (default is true if server_port is 465)
            secure: true
            # Optional (recommended) mail server username:
            username: ${{secrets.MAIL_USERNAME}}
            # Optional (recommended) mail server password:
            password: ${{secrets.MAIL_PASSWORD}}
            # Required mail subject:
            subject: test report
            # Required recipients' addresses:
            to: cinats@yandex.ru
            # Required sender full name (address can be skipped):
            from: Sergey Khudyakov # <user@example.com>
            # Optional plain body:
            body: Build job of ${{github.repository}} completed successfully, please find report attached!
            # Optional attachments:
            attachments: Extra_report.html
            